targets:
  $default:
    builders:
      testBuilder:
        enabled: true

builders:
  testBuilder:
    import: 'package:flutterapp/TestMeta.dart'
    builder_factories: ['testBuilder']
    build_extensions: {'.dart': ['.meta.dart']}
    auto_apply: root_package
    build_to: source
