# Generated by Django 4.1.5 on 2023-02-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbaseinfo',
            table='user_base_info',
        ),
    ]
