# Generated by Django 4.1.5 on 2023-02-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_users', '0002_alter_userbaseinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbaseinfo',
            options={'ordering': ['-create_date', '-id'], 'verbose_name': '用户信息表'},
        ),
    ]
