# Generated by Django 4.1.5 on 2023-02-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_users', '0003_alter_userbaseinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbaseinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'disable')], verbose_name='状态'),
        ),
    ]
