# Generated by Django 4.1.5 on 2023-02-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_users', '0005_alter_userbaseinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbaseinfo',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name='用户名称'),
        ),
    ]
